import { describe, expect, test } from "vitest";
import formatNormalize from "./formatNormalize";

describe("formatNormalize", () => {
	test("should have correct plugin name", () => {
		const plugin = formatNormalize();
		expect(plugin.name).toBe("format");
	});

	test("should default to esm + cjs when format is undefined", () => {
		const plugin = formatNormalize();
		const config = { format: undefined };
		const result = plugin.normalize?.(config, {});
		expect(result?.format).toHaveProperty("esm");
		expect(result?.format).toHaveProperty("cjs");
		// @ts-expect-error format is an object here
		expect(result?.format.esm.sourcemap).toBe(true);
		// @ts-expect-error format is an object here
		expect(result?.format.esm.outputOptions.postBanner).toBe(
			"// @generated by tsdown, DO NOT edit it manually",
		);
		// @ts-expect-error format is an object here
		expect(result?.format.esm.outputOptions.postFooter).toBe(
			"// Generated by @kcconfigs/tsdown",
		);
	});

	test("should default to esm + cjs when format is null", () => {
		const plugin = formatNormalize();
		const config = { format: null };
		const result = plugin.normalize?.(config, {});
		expect(result?.format).toHaveProperty("esm");
		expect(result?.format).toHaveProperty("cjs");
	});

	test("should normalize 'esm' string to esm format object", () => {
		const plugin = formatNormalize();
		const config = { format: "esm" };
		const result = plugin.normalize?.(config, {});
		expect(result?.format).toHaveProperty("esm");
		expect(result?.format).not.toHaveProperty("cjs");
	});

	test("should normalize 'es' alias to esm format object", () => {
		const plugin = formatNormalize();
		const config = { format: "es" };
		const result = plugin.normalize?.(config, {});
		expect(result?.format).toHaveProperty("esm");
	});

	test("should normalize 'module' alias to esm format object", () => {
		const plugin = formatNormalize();
		const config = { format: "module" };
		const result = plugin.normalize?.(config, {});
		expect(result?.format).toHaveProperty("esm");
	});

	test("should normalize 'cjs' string to cjs format object", () => {
		const plugin = formatNormalize();
		const config = { format: "cjs" };
		const result = plugin.normalize?.(config, {});
		expect(result?.format).toHaveProperty("cjs");
		expect(result?.format).not.toHaveProperty("esm");
	});

	test("should normalize 'commonjs' alias to cjs format object", () => {
		const plugin = formatNormalize();
		const config = { format: "commonjs" };
		const result = plugin.normalize?.(config, {});
		expect(result?.format).toHaveProperty("cjs");
	});

	test("should normalize 'iife' string to iife format object", () => {
		const plugin = formatNormalize();
		const config = { format: "iife" };
		const result = plugin.normalize?.(config, {});
		expect(result?.format).toHaveProperty("iife");
	});

	test("should normalize 'umd' string to umd format object", () => {
		const plugin = formatNormalize();
		const config = { format: "umd" };
		const result = plugin.normalize?.(config, {});
		expect(result?.format).toHaveProperty("umd");
	});

	test("should normalize array of formats", () => {
		const plugin = formatNormalize();
		const config = { format: ["esm", "cjs"] };
		const result = plugin.normalize?.(config, {});
		expect(result?.format).toHaveProperty("esm");
		expect(result?.format).toHaveProperty("cjs");
	});

	test("should normalize array with aliases", () => {
		const plugin = formatNormalize();
		const config = { format: ["es", "commonjs"] };
		const result = plugin.normalize?.(config, {});
		expect(result?.format).toHaveProperty("esm");
		expect(result?.format).toHaveProperty("cjs");
	});

	test("should normalize object format with aliases", () => {
		const plugin = formatNormalize();
		const config = {
			format: {
				es: { minify: false },
				commonjs: { sourcemap: false },
			},
		};
		const result = plugin.normalize?.(config, {});
		// @ts-expect-error format is an object here
		expect(result?.format.esm.minify).toBe(false);
		// @ts-expect-error format is an object here
		expect(result?.format.cjs.sourcemap).toBe(false);
	});

	test("should normalize object format with standard keys", () => {
		const plugin = formatNormalize();
		const config = {
			format: {
				esm: { minify: false },
				cjs: { sourcemap: false },
			},
		};
		const result = plugin.normalize?.(config, {});
		// @ts-expect-error format is an object here
		expect(result?.format.esm.minify).toBe(false);
		// @ts-expect-error format is an object here
		expect(result?.format.cjs.sourcemap).toBe(false);
	});

	test("should normalize object format with module alias", () => {
		const plugin = formatNormalize();
		const config = {
			format: {
				module: { minify: false },
			},
		};
		const result = plugin.normalize?.(config, {});
		// @ts-expect-error format is an object here
		expect(result?.format.esm.minify).toBe(false);
	});

	test("should handle empty object format", () => {
		const plugin = formatNormalize();
		const config = {
			format: {},
		};
		const result = plugin.normalize?.(config, {});
		expect(result?.format).toEqual({});
	});

	test("should preserve other config properties", () => {
		const plugin = formatNormalize();
		const config = { entry: ["./src/index.ts"], format: "esm" };
		const result = plugin.normalize?.(config, {});
		expect(result?.entry).toEqual(["./src/index.ts"]);
		expect(result?.format).toHaveProperty("esm");
	});
});
