## https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: perf
      include: scope
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "01:00" ## UTC
    commit-message:
      prefix: perf
      include: scope
