# $schema: https://raw.githubusercontent.com/evilmartians/lefthook/v2.0.9/schema.json

extends:
  - ./node_modules/@kcconfigs/lefthook/src/features/minimal-output.yaml
  - ./node_modules/@kcconfigs/lefthook/src/features/strict.yaml
