## https://ls-lint.org/2.3/configuration/the-basics.html

ls:
  ## All yml must convert to yaml
  .yml: exists:0
  ## All markdown must convert to md
  .markdown: exists:0
  .mkdown: exists:0
  .mdown: exists:0
  .mdwn: exists:0
  .mkdn: exists:0
  .mkd: exists:0
  ## All text files must convert to txt
  .text: exists:0

  .github:
    ## mergify config extension must be yml
    .yml: regex:mergify | exists:1

  ## workflows directory must contains only <kebab-case>.yaml files
  ## and no directory
  .github/workflows:
    "*":
      .dir: exists:0
    .*: exists:0
    .yaml: kebab-case

  ## linters config must contains only <kebab-case>.* files
  ## and no directory
  .github/linters:
    "*":
      .dir: exists:0
    .*: kebab-case

  ## release-please config must contains only config.json and manifest.json
  ## no additional file or directory allowed
  .github/release-please:
    "*":
      .dir: exists:0
    .*: exists:0
    .json: regex:(config|manifest) | exists:2

  ## @kctypes/* name must be lower case with underscore allowed
  packages/@kctypes:
    "*":
      .dir: regex:[a-z][a-z_]+
  ## @kctypes/*/src must contains only .d.ts files in PascalCase or camelCase
  packages/@kctypes/*/types:
    .dir: camelCase
    .*: exists:0
    .d.ts: camelCase | PascalCase

  packages/*:
    ## Scope name must start with @ and all lowercase with dash or dot only
    .dir: regex:@[a-z-.]+
    "*":
      ## Package name must be lower case with dot, underscore, and dash allowed
      .dir: regex:[a-z_][a-z-_.]+

  packages/*/*/src:
    # Source code directory must be camelCase or special __mocks__ folder
    .dir: camelCase | regex:(__mocks__|__fixtures__)
    ## TODO: This doesn't works
    # .{ts,tsx}: camelCase | PascalCase
    # .{css,scss}: camelCase

  packages/*/*/src/hooks:
    ## Hooks directory is named by hook name
    .dir: regex:.*

ignore:
  - assets
  - docs
  - node_modules
  - dist
  - reports
  ## Optimized for speed workaround
  ## https://github.com/loeffel-io/ls-lint/issues/246
  - packages/@kcconfigs/*/node_modules
  - packages/@kcexamples/*/node_modules
  - packages/@kcinternals/*/node_modules
  - packages/@kcstyles/*/node_modules
  - packages/@kctools/*/node_modules
  - packages/@kctypes/*/node_modules
  - packages/@kcws/*/node_modules
  - packages/@kcconfigs/*/dist
  - packages/@kcexamples/*/dist
  - packages/@kcexamples/*/dist.dts
  - packages/@kcexamples/*/dist.tsdown
  - packages/@kcexamples/*/dist.vite
  - packages/@kcexamples/*/dist.zshy
  - packages/@kcinternals/*/dist
  - packages/@kcstyles/*/dist
  - packages/@kctools/*/dist
  - packages/@kctypes/*/dist
  - packages/@kcws/*/dist
  - packages/@kcconfigs/*/reports
  - packages/@kcexamples/*/reports
  - packages/@kcinternals/*/reports
  - packages/@kcstyles/*/reports
  - packages/@kctools/*/reports
  - packages/@kctypes/*/reports
  - packages/@kcws/*/reports
