## https://textlint.org/docs/configuring/
## https://github.com/super-linter/super-linter/blob/main/dependencies/package.json

rules:
  "@kcconfigs/textlint/preset-default": true

filters:
  comments: true
  allowlist:
    allowlistConfigPaths:
      - ./textlintrc.allow.yaml
