import {
	defineConfig as _defineConfig,
	type UserConfig as _UserConfig,
} from "tsdown";

/**
 * @public Custom User Config exported from defineConfig function
 */
export type UserConfig = _UserConfig[];

/**
 * @public Defines the configuration for tsdown.
 * @param configs UserConfig for tsdown
 * @returns The merged UserConfig
 */
export const defineConfig = (
	config?: _UserConfig,
	...configs: UserConfig
): UserConfig => {
	const { format, dts, ...rest } = config ?? ({} as _UserConfig);

	let _dts = dts;
	if (_dts === undefined || _dts === null) {
		_dts = {
			sourcemap: true,
			resolve: false,
		};
	} else if (typeof _dts === "object") {
		_dts.sourcemap ??= true;
		_dts.resolve = false;
	}

	const footer = "// Generated by @kcconfigs/tsdown";
	let _format = format;
	if (_format === undefined || _format === null) {
		_format = {
			esm: {
				sourcemap: true,
				footer,
			},
			cjs: {
				sourcemap: true,
				footer,
			},
		};
	} else if (Array.isArray(_format)) {
		_format = _format.reduce(
			(obj, fmt) => {
				obj[fmt] = {
					sourcemap: true,
					footer,
				};
				return obj;
			},
			{} as Exclude<_UserConfig["format"], undefined | string | Array<unknown>>,
		);
	} else if (typeof _format === "object") {
		_format = Object.fromEntries(
			Object.entries(_format).map(([key, value]) => {
				return [key, { sourcemap: true, footer, ...value }];
			}),
		);
	}

	const baseConfig: _UserConfig = {
		entry: ["./src/index.ts"],
		platform: "neutral",
		fixedExtension: false,
		outDir: "dist",
		clean: true,
		publint: true,
		format: _format,
		dts: _dts,
		...rest,
	};

	return _defineConfig([baseConfig].concat(...configs));
};
