import { definePlugin } from "@kcinternals/config-builder";
import { type Format, mergeConfig, type ResolvedConfig } from "tsdown";
import { normalizePriority } from "../constants";
import type { TsdownConfig, TsdownConfigPlugin } from "../models";

type MinimalFormat = Exclude<Format, "es" | "module" | "commonjs">;
type FormatValue = Partial<ResolvedConfig>;
type MinimalFormatObject = Partial<Record<MinimalFormat, FormatValue>>;

const banner = "// @generated by tsdown, DO NOT edit it manually";
const footer = "// Generated by @kcconfigs/tsdown";

const defaultValue = {
	sourcemap: true,
	outputOptions: {
		postBanner: banner,
		postFooter: footer,
	},
} satisfies FormatValue;

const normalizeFormat = (format: Format): MinimalFormatObject => {
	switch (format) {
		case "module":
		case "esm":
		case "es":
			return { esm: defaultValue };
		case "commonjs":
		case "cjs":
			return { cjs: defaultValue };
		case "iife":
			return { iife: defaultValue };
		case "umd":
			return { umd: defaultValue };
		default:
			return {};
	}
};

const normalize = (config: TsdownConfig): MinimalFormatObject => {
	const format = config.format;
	const defaultFormat = {
		cjs: defaultValue,
		esm: defaultValue,
	};
	if (format === undefined || format === null) return defaultFormat;
	if (typeof format === "string") return normalizeFormat(format as Format);
	if (Array.isArray(format))
		return format.reduce(
			(acc, f) => Object.assign(acc, normalizeFormat(f)),
			{} satisfies MinimalFormatObject,
		);

	const emptyFormat = {} as MinimalFormatObject;
	const es = format.es ?? format.esm ?? format.module;
	if (es) emptyFormat.esm = es;
	const cjs = format.cjs ?? format.commonjs;
	if (cjs) emptyFormat.cjs = cjs;
	const iife = format.iife;
	if (iife) emptyFormat.iife = iife;
	const umd = format.umd;
	if (umd) emptyFormat.umd = umd;

	return emptyFormat;
};

const formatNormalize = (): TsdownConfigPlugin<"format"> =>
	definePlugin("format", {
		configPriority: normalizePriority,
		applyConfig: (config) => {
			return mergeConfig(config, {
				format: normalize(config),
			});
		},
	});
export default formatNormalize;
