import { describe, expect, test } from "vitest";
import formatNormalize from "./formatNormalize";

describe("formatNormalize", () => {
	test("should have correct plugin name", () => {
		const plugin = formatNormalize();
		expect(plugin.name).toBe("format");
	});

	test("should default to esm + cjs when format is undefined", () => {
		const plugin = formatNormalize();
		const config = { format: undefined };
		const result = plugin.applyConfig?.(config as any);
		expect(result?.format).toHaveProperty("esm");
		expect(result?.format).toHaveProperty("cjs");
		// @ts-expect-error format is an object here
		expect(result?.format.esm.sourcemap).toBe(true);
		// @ts-expect-error format is an object here
		expect(result?.format.esm.outputOptions.postBanner).toBe(
			"// @generated by tsdown, DO NOT edit it manually",
		);
		// @ts-expect-error format is an object here
		expect(result?.format.esm.outputOptions.postFooter).toBe(
			"// Generated by @kcconfigs/tsdown",
		);
	});

	test.each([
		[
			"should default to esm + cjs when format is null",
			{ format: null },
			["esm", "cjs"],
			[],
		],
		[
			"should normalize 'esm' string to esm format object",
			{ format: "esm" },
			["esm"],
			["cjs"],
		],
		[
			"should normalize 'es' alias to esm format object",
			{ format: "es" },
			["esm"],
			[],
		],
		[
			"should normalize 'module' alias to esm format object",
			{ format: "module" },
			["esm"],
			[],
		],
		[
			"should normalize 'cjs' string to cjs format object",
			{ format: "cjs" },
			["cjs"],
			["esm"],
		],
		[
			"should normalize 'commonjs' alias to cjs format object",
			{ format: "commonjs" },
			["cjs"],
			[],
		],
		[
			"should normalize 'iife' string to iife format object",
			{ format: "iife" },
			["iife"],
			[],
		],
		[
			"should normalize 'umd' string to umd format object",
			{ format: "umd" },
			["umd"],
			[],
		],
		[
			"should normalize array of formats",
			{ format: ["esm", "cjs"] },
			["esm", "cjs"],
			[],
		],
		[
			"should normalize array with aliases",
			{ format: ["es", "commonjs"] },
			["esm", "cjs"],
			[],
		],
	])("%s", (_name, input, hasProps, notHasProps) => {
		const plugin = formatNormalize();
		const result = plugin.applyConfig?.(input as any);
		for (const prop of hasProps) {
			expect(result?.format).toHaveProperty(prop);
		}
		for (const prop of notHasProps) {
			expect(result?.format).not.toHaveProperty(prop);
		}
	});

	test.each([
		[
			"should normalize object format with aliases",
			{ format: { es: { minify: false }, commonjs: { sourcemap: false } } },
			[
				["esm", "minify", false],
				["cjs", "sourcemap", false],
			] as const,
		],
		[
			"should normalize object format with standard keys",
			{ format: { esm: { minify: false }, cjs: { sourcemap: false } } },
			[
				["esm", "minify", false],
				["cjs", "sourcemap", false],
			] as const,
		],
		[
			"should normalize object format with module alias",
			{ format: { module: { minify: false } } },
			[["esm", "minify", false]] as const,
		],
		[
			"should normalize object format with iife key",
			{ format: { iife: { minify: false } } },
			[["iife", "minify", false]] as const,
		],
		[
			"should normalize object format with umd key",
			{ format: { umd: { minify: false } } },
			[["umd", "minify", false]] as const,
		],
	])("%s", (_name, input, checks) => {
		const plugin = formatNormalize();
		const result = plugin.applyConfig?.(input as any);
		const format = result?.format as Record<string, Record<string, unknown>>;
		for (const [key, prop, value] of checks) {
			expect(format[key][prop]).toBe(value);
		}
	});

	test("should handle empty object format", () => {
		const plugin = formatNormalize();
		const config = {
			format: {},
		};
		const result = plugin.applyConfig?.(config as any);
		expect(result?.format).toEqual({});
	});

	test("should return empty object for unknown format string", () => {
		const plugin = formatNormalize();
		const result = plugin.applyConfig?.({ format: "unknown" as any });
		expect(result?.format).toEqual({});
	});

	test("should preserve other config properties", () => {
		const plugin = formatNormalize();
		const config = { entry: ["./src/index.ts"], format: "esm" as const };
		const result = plugin.applyConfig?.(config as any);
		expect(result?.entry).toEqual(["./src/index.ts"]);
		expect(result?.format).toHaveProperty("esm");
	});
});
