import { describe, expect, test } from "vitest";
import formatNormalize from "./formatNormalize";

describe("formatNormalize", () => {
	test("should have correct plugin name", () => {
		const plugin = formatNormalize();
		expect(plugin.name).toBe("format");
	});

	test("should default to esm + cjs when format is undefined", () => {
		const plugin = formatNormalize();
		const config = { format: undefined };
		const result = plugin.applyConfig?.(config as any);
		expect(result?.format).toHaveProperty("esm");
		expect(result?.format).toHaveProperty("cjs");
		// @ts-expect-error format is an object here
		expect(result?.format.esm.sourcemap).toBe(true);
		// @ts-expect-error format is an object here
		expect(result?.format.esm.outputOptions.postBanner).toBe(
			"// @generated by tsdown, DO NOT edit it manually",
		);
		// @ts-expect-error format is an object here
		expect(result?.format.esm.outputOptions.postFooter).toBe(
			"// Generated by @kcconfigs/tsdown",
		);
	});

	test.for([
		{
			name: "should default to esm + cjs when format is null",
			input: { format: null },
			hasProps: ["esm", "cjs"],
			notHasProps: [],
		},
		{
			name: "should normalize 'esm' string to esm format object",
			input: { format: "esm" },
			hasProps: ["esm"],
			notHasProps: ["cjs"],
		},
		{
			name: "should normalize 'es' alias to esm format object",
			input: { format: "es" },
			hasProps: ["esm"],
			notHasProps: [],
		},
		{
			name: "should normalize 'module' alias to esm format object",
			input: { format: "module" },
			hasProps: ["esm"],
			notHasProps: [],
		},
		{
			name: "should normalize 'cjs' string to cjs format object",
			input: { format: "cjs" },
			hasProps: ["cjs"],
			notHasProps: ["esm"],
		},
		{
			name: "should normalize 'commonjs' alias to cjs format object",
			input: { format: "commonjs" },
			hasProps: ["cjs"],
			notHasProps: [],
		},
		{
			name: "should normalize 'iife' string to iife format object",
			input: { format: "iife" },
			hasProps: ["iife"],
			notHasProps: [],
		},
		{
			name: "should normalize 'umd' string to umd format object",
			input: { format: "umd" },
			hasProps: ["umd"],
			notHasProps: [],
		},
		{
			name: "should normalize array of formats",
			input: { format: ["esm", "cjs"] },
			hasProps: ["esm", "cjs"],
			notHasProps: [],
		},
		{
			name: "should normalize array with aliases",
			input: { format: ["es", "commonjs"] },
			hasProps: ["esm", "cjs"],
			notHasProps: [],
		},
	])("$name", ({ input, hasProps, notHasProps }) => {
		const plugin = formatNormalize();
		const result = plugin.applyConfig?.(input as any);
		for (const prop of hasProps) {
			expect(result?.format).toHaveProperty(prop);
		}
		for (const prop of notHasProps) {
			expect(result?.format).not.toHaveProperty(prop);
		}
	});

	test.for([
		{
			name: "should normalize object format with aliases",
			input: {
				format: { es: { minify: false }, commonjs: { sourcemap: false } },
			},
			checks: [
				["esm", "minify", false],
				["cjs", "sourcemap", false],
			] as const,
		},
		{
			name: "should normalize object format with standard keys",
			input: { format: { esm: { minify: false }, cjs: { sourcemap: false } } },
			checks: [
				["esm", "minify", false],
				["cjs", "sourcemap", false],
			] as const,
		},
		{
			name: "should normalize object format with module alias",
			input: { format: { module: { minify: false } } },
			checks: [["esm", "minify", false]] as const,
		},
		{
			name: "should normalize object format with iife key",
			input: { format: { iife: { minify: false } } },
			checks: [["iife", "minify", false]] as const,
		},
		{
			name: "should normalize object format with umd key",
			input: { format: { umd: { minify: false } } },
			checks: [["umd", "minify", false]] as const,
		},
	])("$name", ({ input, checks }) => {
		const plugin = formatNormalize();
		const result = plugin.applyConfig?.(input as any);
		const format = result?.format as Record<string, Record<string, unknown>>;
		for (const [key, prop, value] of checks) {
			expect(format[key]?.[prop]).toBe(value);
		}
	});

	test("should handle empty object format", () => {
		const plugin = formatNormalize();
		const config = {
			format: {},
		};
		const result = plugin.applyConfig?.(config as any);
		expect(result?.format).toEqual({});
	});

	test("should return empty object for unknown format string", () => {
		const plugin = formatNormalize();
		const result = plugin.applyConfig?.({ format: "unknown" as any });
		expect(result?.format).toEqual({});
	});

	test("should preserve other config properties", () => {
		const plugin = formatNormalize();
		const config = { entry: ["./src/index.ts"], format: "esm" as const };
		const result = plugin.applyConfig?.(config as any);
		expect(result?.entry).toEqual(["./src/index.ts"]);
		expect(result?.format).toHaveProperty("esm");
	});
});
