import type { Format, ResolvedConfig } from "tsdown";

type MinimalFormat = Exclude<Format, "es" | "module" | "commonjs">;
type FormatValue = Partial<ResolvedConfig>;
type FormatObject = Partial<Record<Format, FormatValue>>;
export type MinimalFormatObject = Partial<Record<MinimalFormat, FormatValue>>;
export type FormatOption = Format | Array<Format> | FormatObject;

const banner = "// @generated by tsdown, DO NOT edit it manually";
const footer = "// Generated by @kcconfigs/tsdown";

export const defineFormat = (
	format: WithUndefined<FormatOption>,
): WithUndefined<MinimalFormatObject> => {
	const defaultFormat = {
		esm: {
			sourcemap: true,
			outputOptions: {
				postBanner: banner,
				postFooter: footer,
			},
		} satisfies FormatValue,
		cjs: {
			sourcemap: true,
			outputOptions: {
				postBanner: banner,
				postFooter: footer,
			},
		} satisfies FormatValue,
	};

	if (typeof format === "string") {
		switch (format) {
			case "module":
			case "esm":
			case "es":
				return { esm: defaultFormat.esm };
			case "commonjs":
			case "cjs":
				return { cjs: defaultFormat.cjs };
		}
	} else if (Array.isArray(format)) {
		return format.reduce<MinimalFormatObject>((prev, curr) => {
			return Object.assign(prev, defineFormat(curr));
		}, {} as MinimalFormatObject);
	} else if (typeof format === "object") {
		return Object.assign(defaultFormat, format);
	}

	return defaultFormat;
};
