import type { Format, ResolvedConfig } from "tsdown";

type FormatValue = Partial<ResolvedConfig>;
type FormatObject = Partial<Record<Format, FormatValue>>;
type FormatOption = Format | Array<Format> | FormatObject;

const banner = "// @generated by tsdown, DO NOT edit it manually";
const footer = "// Generated by @kcconfigs/tsdown";

export const defineFormat = (
	format: WithUndefined<FormatOption>,
): WithUndefined<FormatObject> => {
	const defaultFormat: FormatObject = {
		esm: {
			sourcemap: true,
			outputOptions: {
				postBanner: banner,
				postFooter: footer,
			},
		},
		cjs: {
			sourcemap: true,
			cjsDefault: false,
			outputOptions: {
				postBanner: banner,
				postFooter: footer,
			},
		},
	};

	if (typeof format === "string") {
		switch (format) {
			case "module":
			case "esm":
			case "es":
				return { esm: defaultFormat.esm };
			case "commonjs":
			case "cjs":
				return { cjs: defaultFormat.cjs };
		}
	} else if (Array.isArray(format)) {
		return format.reduce<FormatObject>((prev, curr) => {
			return Object.assign(prev, defineFormat(curr));
		}, {} as FormatObject);
	} else if (typeof format === "object") {
		return Object.assign(defaultFormat, format);
	}

	return defaultFormat;
};
