name: Main

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commitcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Set up source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: Set up nodejs
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: package.json
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile ## (dependabot/dependabot-core#12244)
      - name: Validate current commit
        if: github.event_name == 'push'
        run: pnpm check:commit --last --verbose
      - name: Validate pull-request title
        if: github.event_name == 'pull_request'
        run: echo "$PR_TITLE" | pnpm check:commit --verbose
        env:
          PR_TITLE: "${{ github.event.pull_request.title }}"

  licensecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Set up source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Scan dependencies
        uses: fossas/fossa-action@c414b9ad82eaad041e47a7cf62a4f02411f427a0 # v1.8.0
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
      - name: Test dependencies
        uses: fossas/fossa-action@c414b9ad82eaad041e47a7cf62a4f02411f427a0 # v1.8.0
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          run-tests: true

  zizmorcheck:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Set up source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Run Security Analysis with Zizmor
        uses: zizmorcore/zizmor-action@0dce2577a4760a2749d8cfb7a84b7d5585ebcb7d # v0.5.0
        with:
          config: .github/linters/zizmor.yaml

  megalintcheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write ## Write commit statuses
      pull-requests: write ## Write pull-request comments
      security-events: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: MegaLinter
        uses: oxsecurity/megalinter/flavors/javascript@42bb470545e359597e7f12156947c436e4e3fb9a # v9.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MEGALINTER_CONFIG: .github/linters/.mega-linter.yaml
          ## Disable lychee (broken links checker) errors on release pull requests
          SPELL_LYCHEE_DISABLE_ERRORS: "${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'autorelease: pending') && 'true' || 'false' }}"
          ## Disable grype (vulnerability scanner) errors on Dependabot pull requests
          REPOSITORY_GRYPE_DISABLE_ERRORS: "${{ github.event_name == 'pull_request' && github.actor == 'dependabot[bot]' && 'true' || 'false' }}"
      ## NOTE: disable for now as it creates too much noise in the logs
      # - name: Upload MegaLinter results to GitHub Security tab
      #   if: success() || failure()
      #   uses: github/codeql-action/upload-sarif@5d4e8d1aca955e8d8589aabd499c5cae939e33c7 # v4.31.9
      #   with:
      #     sarif_file: "megalinter-reports/megalinter-report.sarif"
      - name: Upload MegaLinter reports
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: success() || failure()
        with:
          name: MegaLinter reports
          include-hidden-files: "true"
          path: |
            megalinter-reports
            mega-linter.log

  main:
    runs-on: ubuntu-latest
    needs:
      - commitcheck
      - licensecheck
      - zizmorcheck
    steps:
      - name: Set up source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: Set up nodejs
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: package.json
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile ## (dependabot/dependabot-core#12244)
      - name: Check terminology
        run: pnpm check:text:ci
      - name: Check code styles
        run: pnpm check:all
      - name: Build packages
        run: pnpm build:all
      - name: Test packages
        run: pnpm test:all
      - name: Scan source code
        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9 # v7.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: test-results
          path: reports
          retention-days: 5

  testing:
    runs-on: ubuntu-latest
    needs:
      - main
    strategy:
      matrix:
        # https://nodejs.org/en/about/previous-releases
        node-version: [20, 22, 24, 25]
    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Set up nodejs
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile ## (dependabot/dependabot-core#12244)

      - name: Build packages
        run: pnpm build:all

      - name: Test packages
        run: pnpm test:all

  ## dependabot/dependabot-core#12244
  mitigate-dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    permissions:
      contents: write
    steps:
      - name: Set up source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Set up pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: Set up nodejs
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: package.json
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Commit changes back
        run: |
          git add pnpm-lock.yaml
          git commit --no-verify \
            -m "fix: update pnpm-lock.yaml to mitigate dependabot/dependabot-core#12244 [skip ci]" ||
            exit 0
          git push --no-verify
