name: Main

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commitcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Set up source code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: Set up nodejs
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: package.json
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Validate current commit
        if: github.event_name == 'push'
        run: pnpm check:commit --last --verbose
      - name: Validate pull-request title
        if: github.event_name == 'pull_request'
        run: echo "$PR_TITLE" | pnpm check:commit --verbose
        env:
          PR_TITLE: "${{ github.event.pull_request.title }}"

  licensecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Set up source code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Scan dependencies
        uses: fossas/fossa-action@3ebcea1862c6ffbd5cf1b4d0bd6b3fe7bd6f2cac # v1.7.0
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
      - name: Test dependencies
        uses: fossas/fossa-action@3ebcea1862c6ffbd5cf1b4d0bd6b3fe7bd6f2cac # v1.7.0
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          run-tests: true

  zizmorcheck:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Set up source code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Run Security Analysis with Zizmor
        uses: zizmorcore/zizmor-action@e639db99335bc9038abc0e066dfcd72e23d26fb4 # v0.3.0
        with:
          config: .github/linters/zizmor.yaml

  megalintcheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      security-events: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: MegaLinter
        uses: oxsecurity/megalinter/flavors/javascript@55a59b24a441e0e1943080d4a512d827710d4a9d # v9.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MEGALINTER_CONFIG: .github/linters/.mega-linter.yaml
          ## Disable lychee errors on pull requests to reduce noise
          SPELL_LYCHEE_DISABLE_ERRORS: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'autorelease: pending') && 'true' || 'false' }}
      ## NOTE: disable for now as it creates too much noise in the logs
      # - name: Upload MegaLinter results to GitHub Security tab
      #   if: success() || failure()
      #   uses: github/codeql-action/upload-sarif@5d4e8d1aca955e8d8589aabd499c5cae939e33c7 # v4.31.9
      #   with:
      #     sarif_file: "megalinter-reports/megalinter-report.sarif"
      - name: Upload MegaLinter reports
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: success() || failure()
        with:
          name: MegaLinter reports
          include-hidden-files: "true"
          path: |
            megalinter-reports
            mega-linter.log

  main:
    runs-on: ubuntu-latest
    needs:
      - commitcheck
      - licensecheck
      - zizmorcheck
    steps:
      - name: Set up source code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: Set up nodejs
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: package.json
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check terminology
        run: pnpm check:text:ci
      - name: Check code styles
        run: pnpm check:all
      - name: Build packages
        run: pnpm build:all
      - name: Test packages
        run: pnpm test:all
      - name: Scan source code
        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9 # v7.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: test-results
          path: reports
          retention-days: 5

  testing:
    runs-on: ubuntu-latest
    needs:
      - main
    strategy:
      matrix:
        # https://nodejs.org/en/about/previous-releases
        node-version: [20, 22, 24, 25]
    steps:
      - name: Checkout source code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Set up nodejs
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build:all

      - name: Test packages
        run: pnpm test:all
