name: Publish beta

on:
  release:
    types:
      - prereleased

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'start publishing rc/beta/alpha tag...'
