name: Publish latest

on:
  release:
    types:
      - released

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'start publishing latest tag...'
