name: Publish packages

on:
  release:
    types:
      - published

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: production
      ## Use outputs from publish script to set the URL dynamically
      url: https://www.npmjs.com/package/${{ steps.publish.outputs.package }}/v/${{ steps.publish.outputs.version }}
    steps:
      - name: Set up source code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up runtime
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
        with:
          require-lockfile: true
          cache: true
      - name: Build configurations
        run: pnpm build:config
      - name: Publish version
        id: publish
        run: bash ./scripts/package-publish.sh
